x = int(input('Digite alguma coisa: '))
print('O tipo primitivo desse valor é: {} '.format(type(x)))
print('Só tem espaços?', x.isspace())
print('É um número?', x.isalnum())
print('É alfabético?', x.isalpha())
print('É alfanumérico?', x.isalnum())
print('Está em maiúscula?', x.isupper())
print('Está em minúscula?', x.islower())
print('Está capitalizada?', x.istitle())
#print('É um número decimal?', x.isdecimal())
